services:
  minecraft:
    container_name: minecraft
    image: itzg/minecraft-server:java17
    volumes:
      - minecraft:/data
    environment:
      DIFFICULTY: normal
      ENABLE_ROLLING_LOGS: "true"
      ENABLE_WHITELIST: "true"
      ENFORCE_WHITELIST: "true"
      EULA: "true"
      FORCE_GAMEMODE: "true"
      MAX_PLAYERS: 10
      MEMORY: 8G
      MOTD: The Fryer's Minecraft Server
      NETWORK_COMPRESSION_THRESHOLD: 512
      OPS: FryyourBacon
      OVERRIDE_SERVER_PROPERTIES: "true"
      OVERRIDE_WHITELIST: "true"
      PACKWIZ_URL: https://raw.githubusercontent.com/caycehouse/fabulously-optimized-server/master/pack.toml
      RCON_CMDS_STARTUP: |-
        gamerule doFireTick false
        gamerule playersSleepingPercentage 0
        scoreboard objectives setdisplay list ts_Deaths
      SNOOPER_ENABLED: "false"
      SIMULATION_DISTANCE: 4
      SYNC_CHUNK_WRITES: "false"
      TYPE: FABRIC
      TZ: America/New_York
      USE_AIKAR_FLAGS: "true"
      VANILLATWEAKS_SHARECODE: IvCbZR,xnqI8i
      VERSION: 1.19
      VIEW_DISTANCE: 7
      WHITELIST: FryyourBacon,TrooperMikey,BongoSongo5,XCosmicPenguin,Mygreenburrito,gusano_18,ScrambleYourEggs,_Leslie_,Chappy___,Polypon,P_B_Butterscotch,prunejuice,egggz56,fedorakin
    ports:
      - 25565:25565
    restart: unless-stopped
    tty: true
    stdin_open: true

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: America/New_York
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_SCHEDULE: 0 0 4 * * *
      WATCHTOWER_TIMEOUT: 300s
    restart: unless-stopped

volumes:
  minecraft: {}
