services:
  archisteamfarm:
    container_name: archisteamfarm
    image: justarchi/archisteamfarm
    volumes:
      - config:/app/config
    ports:
      - 1242:1242/tcp
    restart: unless-stopped

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: America/New_York
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_SCHEDULE: 0 0 4 * * *
      WATCHTOWER_TIMEOUT: 300s
    restart: unless-stopped

volumes:
  config: {}
