services:
  oceanblock:
    container_name: oceanblock
    image: itzg/minecraft-server:java8-multiarch
    volumes:
      - data:/data
    environment:
      DIFFICULTY: normal
      ENABLE_ROLLING_LOGS: "true"
      ENABLE_WHITELIST: "true"
      ENFORCE_WHITELIST: "true"
      EULA: "true"
      FORCE_GAMEMODE: "true"
      MAX_PLAYERS: 10
      MEMORY: 8G
      MOTD: The Fryer's OceanBlock Server
      NETWORK_COMPRESSION_THRESHOLD: 512
      OPS: FryyourBacon
      OVERRIDE_SERVER_PROPERTIES: "true"
      OVERRIDE_WHITELIST: "true"
      SNOOPER_ENABLED: "false"
      SYNC_CHUNK_WRITES: "false"
      TYPE: FTBA
      TZ: America/New_York
      FTB_MODPACK_ID: 91
      VERSION: 1.16.5
      VIEW_DISTANCE: 7
      WHITELIST: FryyourBacon,ScrambleYourEggs
    ports:
      - 25566:25565
    restart: unless-stopped
    tty: true
    stdin_open: true

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: America/New_York
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_SCHEDULE: 0 0 4 * * *
      WATCHTOWER_TIMEOUT: 300s
    restart: unless-stopped

volumes:
  data: {}
