services:
  vaulthunters:
    container_name: vaulthunters
    image: itzg/minecraft-server:java8
    volumes:
      - data:/data
    environment:
      CF_BASE_DIR: /data
      CF_SERVER_MOD: https://mediafiles.forgecdn.net/files/3853/291/VaultHunters-OfficialModpack-1.13.4-Server.zip
      DIFFICULTY: normal
      ENABLE_COMMAND_BLOCK: "true"
      ENABLE_ROLLING_LOGS: "true"
      ENABLE_WHITELIST: "true"
      ENFORCE_WHITELIST: "true"
      EULA: "true"
      FORCE_GAMEMODE: "true"
      MAX_PLAYERS: 10
      MEMORY: 8G
      MODS: https://mediafiles.forgecdn.net/files/3358/883/dynviewdist-2.0.jar
      MOTD: The Fryer's VaultHunters Server
      NETWORK_COMPRESSION_THRESHOLD: 512
      OPS: FryyourBacon
      OVERRIDE_SERVER_PROPERTIES: "true"
      OVERRIDE_WHITELIST: "true"
      QUERY_PORT: 25565
      SERVER_PORT: 25565
      SNOOPER_ENABLED: "false"
      SIMULATION_DISTANCE: 4
      SYNC_CHUNK_WRITES: "false"
      TYPE: CURSEFORGE
      TZ: America/New_York
      USE_AIKAR_FLAGS: "true"
      VERSION: 1.16.5
      VIEW_DISTANCE: 7
      WHITELIST: FryyourBacon,ScrambleYourEggs
    ports:
      - 25568:25565
    restart: unless-stopped
    tty: true
    stdin_open: true

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: America/New_York
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_SCHEDULE: 0 0 4 * * *
      WATCHTOWER_TIMEOUT: 300s
    restart: unless-stopped

volumes:
  data: {}
