services:
  corekeeper:
    container_name: corekeeper
    image: tedtramonte/core-keeper-server
    volumes:
      - data:/data
    environment:
      DIRECT_CONNECT: 1
    ports:
      - 27015:27015
    restart: unless-stopped

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: America/New_York
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_SCHEDULE: 0 0 4 * * *
      WATCHTOWER_TIMEOUT: 300s
    restart: unless-stopped

volumes:
  data: {}
