services:
  allthemods7:
    container_name: allthemods7
    image: itzg/minecraft-server
    volumes:
      - data:/data
      - modpacks:/modpacks:ro
    environment:
      DIFFICULTY: hard
      ENABLE_ROLLING_LOGS: "true"
      ENABLE_WHITELIST: "true"
      ENFORCE_WHITELIST: "true"
      EULA: "true"
      FORCE_GAMEMODE: "true"
      MAX_PLAYERS: 10
      MEMORY: 8G
      MOTD: The Fryer's All The Mods 7 Server
      NETWORK_COMPRESSION_THRESHOLD: 512
      OPS: FryyourBacon
      OVERRIDE_SERVER_PROPERTIES: "true"
      OVERRIDE_WHITELIST: "true"
      SNOOPER_ENABLED: "false"
      TYPE: FORGE
      GENERIC_PACK: /modpacks/Server-Files-0.4.21.zip
      TZ: America/New_York
      USE_AIKAR_FLAGS: "true"
      VERSION: 1.18.2
      FORGEVERSION: 40.1.60
      WHITELIST: FryyourBacon,ScrambleYourEggs
    ports:
      - 25567:25565
    restart: unless-stopped
    tty: true
    stdin_open: true

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: America/New_York
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_SCHEDULE: 0 0 4 * * *
      WATCHTOWER_TIMEOUT: 300s
    restart: unless-stopped

volumes:
  data: {}
  modpacks: {}
